FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder
WORKDIR /go/src/github.com/openshift/openshift-controller-manager
COPY . .
RUN make build --warn-undefined-variables \
    && make tests-ext-build \
    && gzip openshift-controller-manager-tests-ext

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9
COPY --from=builder /go/src/github.com/openshift/openshift-controller-manager/openshift-controller-manager /usr/bin/
COPY --from=builder /go/src/github.com/openshift/openshift-controller-manager/openshift-controller-manager-tests-ext.gz /usr/bin/
LABEL io.k8s.display-name="OpenShift Controller Manager Command" \
      io.k8s.description="OpenShift is a platform for developing, building, and deploying containerized applications." \
      io.openshift.tags="openshift,openshift-controller-manager"
